### ISSUE TITLE
"Not a directory" panic

### ISSUE THREAD

**Issue by razofz** [stela2502/dense_2_sparse#1]
Hi!

I tried it out, but got some errors. Specifically a panic about NotADirectory. Supplying my run call and subsequent output here:

```bash
RUST_BACKTRACE=full ./target/release/dense2sparse -i testData/DenseMatrix.csv                                                         ─╯
thread 'main' panicked at src/bin/dense2sparse.rs:121:47:
called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
stack backtrace:
   0:        0x102270e1c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h192489893ab3de20
   1:        0x102287820 - core::fmt::write::h2573968dce8b4c8e
   2:        0x102270bec - std::io::Write::write_fmt::hd688b4e0e14280fb
   3:        0x10226623c - std::panicking::default_hook::{{closure}}::h132ab4fd80cbd688
   4:        0x102265d84 - std::panicking::default_hook::h25db1205ededf4a8
   5:        0x1022667c0 - std::panicking::rust_panic_with_hook::h1a5e700ba9552453
   6:        0x10227135c - std::panicking::begin_panic_handler::{{closure}}::h4b087c40eb4a42d9
   7:        0x102271074 - std::sys::backtrace::__rust_end_short_backtrace::heff777664c13f8e2
   8:        0x1022663ac - _rust_begin_unwind
   9:        0x10229512c - core::panicking::panic_fmt::h681f622c7f427738
  10:        0x102295434 - core::result::unwrap_failed::h1f19f54c79dd8694
  11:        0x10218923c - dense2sparse::main::h79651e87518b071e
  12:        0x102191250 - std::sys::backtrace::__rust_begin_short_backtrace::h8ecbf04200070099
  13:        0x102191238 - std::rt::lang_start::{{closure}}::h28aa27ac2895bdc6
  14:        0x10227363c - std::rt::lang_start_internal::h9c7d71c5826f1ac3
  15:        0x102189974 - _main
```

Note: the documentation in the readme specifies to call `target/release/rusty_sparse_mmx`, but after building there were no such binary produced. I therefore assumed it was the `target/release/dense2sparse` that should be used, please correct me if I'm wrong.

Version info:

```bash
./target/release/dense2sparse -V
rusty_sparse_mmx 0.1.0
```

**Comment by stela2502** [comment]
😄
./target/release/dense2sparse -i testData/
It want's the PATH where the csv file(s) would be.
Not perfect, but that is how I implemented it 😉

/Stefan
________________________________
Von: Rasmus Olofzon ***@***.***>
Gesendet: Freitag, 29. November 2024 11:18
An: stela2502/RustySparseMMX ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [stela2502/RustySparseMMX] "Not a directory" panic (Issue #1)


Hi!

I tried it out, but got some errors. Specifically a panic about NotADirectory. Supplying my run call and subsequent output here:

RUST_BACKTRACE=full ./target/release/dense2sparse -i testData/DenseMatrix.csv                                                         ─╯
thread 'main' panicked at src/bin/dense2sparse.rs:121:47:
called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
stack backtrace:
   0:        0x102270e1c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h192489893ab3de20
   1:        0x102287820 - core::fmt::write::h2573968dce8b4c8e
   2:        0x102270bec - std::io::Write::write_fmt::hd688b4e0e14280fb
   3:        0x10226623c - std::panicking::default_hook::{{closure}}::h132ab4fd80cbd688
   4:        0x102265d84 - std::panicking::default_hook::h25db1205ededf4a8
   5:        0x1022667c0 - std::panicking::rust_panic_with_hook::h1a5e700ba9552453
   6:        0x10227135c - std::panicking::begin_panic_handler::{{closure}}::h4b087c40eb4a42d9
   7:        0x102271074 - std::sys::backtrace::__rust_end_short_backtrace::heff777664c13f8e2
   8:        0x1022663ac - _rust_begin_unwind
   9:        0x10229512c - core::panicking::panic_fmt::h681f622c7f427738
  10:        0x102295434 - core::result::unwrap_failed::h1f19f54c79dd8694
  11:        0x10218923c - dense2sparse::main::h79651e87518b071e
  12:        0x102191250 - std::sys::backtrace::__rust_begin_short_backtrace::h8ecbf04200070099
  13:        0x102191238 - std::rt::lang_start::{{closure}}::h28aa27ac2895bdc6
  14:        0x10227363c - std::rt::lang_start_internal::h9c7d71c5826f1ac3
  15:        0x102189974 - _main

Note: the documentation in the readme specifies to call target/release/rusty_sparse_mmx, but after building there were no such binary produced. I therefore assumed it was the target/release/dense2sparse that should be used, please correct me if I'm wrong.

Version info:

./target/release/dense2sparse -V
rusty_sparse_mmx 0.1.0

**Comment by razofz** [comment]
so, to sum up our irl discussion, the input wanted by `-i` is the directory where csv files reside, and the tool will apply to each csv file in the directory. Also if it is tab-separated (tsv). And then the output will be in the same input directory, in a directory with `<the filename minus extension of the input csv file>/filtered_feature_bc_matrix`. 

So e.g. `-i testData` in this repo will result in `testData/DenseMatrix{,_gz}/filtered_feature_bc_matrix/{features.tsv,barcodes.tsv,matrix.mtx}.gz` (using some bash substitutions for brevity)
